### ISSUE TITLE
Missing commander dependency on fresh install

### ISSUE THREAD

**Issue by WithoutPants** [mrodrig/json-2-csv#136]
## Background Information
- Module Version: `3.5.7 `
- Node/Browser Version: `10.16.0`

The issue I'm reporting is with:
- [x] json2csv
- [ ] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [x] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior

After installing using `npm install -g json-2-csv`, then running `json2csv`, the usage information should be displayed.

## Actual Behavior

The following error is output:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\json-2-csv\bin\json2csv.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Installing commander via `npm install -g commander` fixed the issue, but it looks like this needs to be a dependency, or at the very least included in the install instructions.

## Data Sample 

N/A

## Code Example

N/A

**Comment by mrodrig** [comment]
Hi @WithoutPants. Thanks for reporting this. That's definitely an issue. Good find! I'll work on getting that fixed as soon as possible. Thanks again for reporting it!
