### ISSUE TITLE
CLI `csv2json -h` results in an error

### ISSUE THREAD

**Issue by porg** [mrodrig/json-2-csv#262]
## Reproduction

- `csv2json --help`, `json2csv --help` and `json2csv --h` all work fine
- But `$ csv2json -h` results in an error.

## Expected Behavior

- `csv2json -h` Shows the help screen

## Actual Behavior

- Results in an error

```zsh
➜  ~ json2csv --help
Usage: json2csv <jsonFile> [options]

Arguments:
  jsonFile                         JSON file to convert

Options:
  -V, --version                    output the version number
  -o, --output [output]            Path of output file. If not provided, then stdout will be used
  -a, --array-indexes-as-keys      Includes array indexes in the generated keys
  -S, --check-schema               Check for schema differences
  -f, --field <delimiter>          Field delimiter
  -w, --wrap <delimiter>           Wrap delimiter
  -e, --eol <delimiter>            End of Line delimiter
  -E, --empty-field-value <value>  Empty field value
  -n, --expand-nested-objects      Expand nested objects to be deep converted to CSV
  -k, --keys [keys]                Keys of documents to convert to CSV
  -d, --escape-header-nested-dots  Escape header nested dots
  -b, --excel-bom                  Excel Byte Order Mark character prepended to CSV
  -x, --exclude-keys [keys]        Comma separated list of keys to exclude
  -A, --expand-array-objects       Expand array objects
  -W, --without-header             Withhold the prepended header
  -p, --prevent-csv-injection      Prevent CSV Injection
  -s, --sort-header                Sort the header fields
  -F, --trim-fields                Trim field values
  -H, --trim-header                Trim header fields
  -U, --unwind-arrays              Unwind array values to their own CSV line
  -I, --iso-date-format            Use ISO 8601 date format
  -L, --locale-format              Use locale format for values
  -B, --wrap-booleans              Wrap booleans
  -h, --help                       display help for command
➜  ~ json2csv -h    
Usage: json2csv <jsonFile> [options]

Arguments:
  jsonFile                         JSON file to convert

Options:
  -V, --version                    output the version number
  -o, --output [output]            Path of output file. If not provided, then stdout will be used
  -a, --array-indexes-as-keys      Includes array indexes in the generated keys
  -S, --check-schema               Check for schema differences
  -f, --field <delimiter>          Field delimiter
  -w, --wrap <delimiter>           Wrap delimiter
  -e, --eol <delimiter>            End of Line delimiter
  -E, --empty-field-value <value>  Empty field value
  -n, --expand-nested-objects      Expand nested objects to be deep converted to CSV
  -k, --keys [keys]                Keys of documents to convert to CSV
  -d, --escape-header-nested-dots  Escape header nested dots
  -b, --excel-bom                  Excel Byte Order Mark character prepended to CSV
  -x, --exclude-keys [keys]        Comma separated list of keys to exclude
  -A, --expand-array-objects       Expand array objects
  -W, --without-header             Withhold the prepended header
  -p, --prevent-csv-injection      Prevent CSV Injection
  -s, --sort-header                Sort the header fields
  -F, --trim-fields                Trim field values
  -H, --trim-header                Trim header fields
  -U, --unwind-arrays              Unwind array values to their own CSV line
  -I, --iso-date-format            Use ISO 8601 date format
  -L, --locale-format              Use locale format for values
  -B, --wrap-booleans              Wrap booleans
  -h, --help                       display help for command
➜  ~ json2csv -h
Usage: json2csv <jsonFile> [options]

Arguments:
  jsonFile                         JSON file to convert

Options:
  -V, --version                    output the version number
  -o, --output [output]            Path of output file. If not provided, then stdout will be used
  -a, --array-indexes-as-keys      Includes array indexes in the generated keys
  -S, --check-schema               Check for schema differences
  -f, --field <delimiter>          Field delimiter
  -w, --wrap <delimiter>           Wrap delimiter
  -e, --eol <delimiter>            End of Line delimiter
  -E, --empty-field-value <value>  Empty field value
  -n, --expand-nested-objects      Expand nested objects to be deep converted to CSV
  -k, --keys [keys]                Keys of documents to convert to CSV
  -d, --escape-header-nested-dots  Escape header nested dots
  -b, --excel-bom                  Excel Byte Order Mark character prepended to CSV
  -x, --exclude-keys [keys]        Comma separated list of keys to exclude
  -A, --expand-array-objects       Expand array objects
  -W, --without-header             Withhold the prepended header
  -p, --prevent-csv-injection      Prevent CSV Injection
  -s, --sort-header                Sort the header fields
  -F, --trim-fields                Trim field values
  -H, --trim-header                Trim header fields
  -U, --unwind-arrays              Unwind array values to their own CSV line
  -I, --iso-date-format            Use ISO 8601 date format
  -L, --locale-format              Use locale format for values
  -B, --wrap-booleans              Wrap booleans
  -h, --help                       display help for command
➜  ~ csv2json --help
Usage: csv2json <csvFile> [options]

Arguments:
  csvFile                      CSV file to convert

Options:
  -V, --version                output the version number
  -o, --output [output]        Path of output file. If not provided, then stdout will be used
  -f, --field <delimiter>      Field delimiter
  -w, --wrap <delimiter>       Wrap delimiter
  -e, --eol <delimiter>        End of Line delimiter
  -b, --excel-bom              Excel Byte Order Mark character prepended to CSV
  -p, --prevent-csv-injection  Prevent CSV Injection
  -F, --trim-fields            Trim field values
  -H, --trim-header            Trim header fields
  -h, --header-fields          Specify the fields names in place a header line in the CSV itself
  -k, --keys [keys]            Keys of documents to convert to CSV
  --help                       display help for command
➜  ~ csv2json -h    
/usr/local/lib/node_modules/@mrodrig/json-2-csv-cli/node_modules/commander/lib/command.js:581
      throw err;
      ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Option.constructKeysList [as parseArg] (/usr/local/lib/node_modules/@mrodrig/json-2-csv-cli/bin/utils/utils.js:88:17)
    at Command._callParseArg (/usr/local/lib/node_modules/@mrodrig/json-2-csv-cli/node_modules/commander/lib/command.js:575:21)
    at handleOptionValue (/usr/local/lib/node_modules/@mrodrig/json-2-csv-cli/node_modules/commander/lib/command.js:674:20)
    at Command.<anonymous> (/usr/local/lib/node_modules/@mrodrig/json-2-csv-cli/node_modules/commander/lib/command.js:694:7)
    at Command.emit (node:events:520:28)
    at Command.parseOptions (/usr/local/lib/node_modules/@mrodrig/json-2-csv-cli/node_modules/commander/lib/command.js:1689:18)
    at Command._parseCommand (/usr/local/lib/node_modules/@mrodrig/json-2-csv-cli/node_modules/commander/lib/command.js:1449:25)
    at Command.parse (/usr/local/lib/node_modules/@mrodrig/json-2-csv-cli/node_modules/commander/lib/command.js:1064:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@mrodrig/json-2-csv-cli/bin/csv2json.js:23:6)
    at Module._compile (node:internal/modules/cjs/loader:1504:14)

Node.js v22.5.1
➜  ~ 

```

## Background Information
- Module Version: `5.5.5`
- Node: `v22.5.1`
- OS: macOS 13.6.9 Ventura

The issue I'm reporting is with:
- [ ] json2csv
- [x] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [x] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).
- verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
  - does not apply as my bug occurs with `csv2json -h` which uses no input/output at all.

**Comment by porg** [comment]
@mrodrig it's a minor bug but still I'd appreciate a reaction. Thanks!
